services:
  api:
    build: ./WebApi
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend: 
    build: ./WebFrontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - my-network

networks: 
  my-network: 
    driver: bridge
